services:
  meilisearch:
    image: getmeili/meilisearch:v1.1
    container_name: meilisearch-blog
    ports: 
      - 7700:7700
    restart: unless-stopped
    volumes:
      - data.ms:/data.ms
    environment:
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY}

volumes:
  data.ms:

